# This file is machine-generated - editing it directly is not advised

[[CEnum]]
git-tree-sha1 = "018a008c61eb9e422dfabbdd6f4ceba8adff9544"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
